complexity:
  TooManyFunctions:
    thresholdInClasses: 20

comments:
  excludes: "**/test/**,**/androidTest/**,**/*.Test.kt,**/*.Spec.kt,**/*.Spek.kt"
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false

style:
  DataClassShouldBeImmutable:
    active: false

potential-bugs:
  UnsafeCallOnNullableType:
    excludes: "**/test/**,**/androidTest/**,**/*.Test.kt,**/*.Spec.kt,**/*.Spek.kt"
  UnsafeCast:
    excludes: "**/test/**,**/androidTest/**,**/*.Test.kt,**/*.Spec.kt,**/*.Spek.kt"
