name: Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android-test:
    name: "Android"
    runs-on: ubuntu-latest
    timeout-minutes: 80

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Run tests
        run: ./gradlew testAndroidHost

      - name: Save Test Results
        uses: actions/upload-artifact@v6
        if: ${{ always() }}
        with:
          name: test-results-android
          path: |
            **/build/reports/tests/
          retention-days: 7

  ios-test:
    name: "iOS"
    runs-on: macos-15
    timeout-minutes: 80

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Run tests
        run: ./gradlew iosSimulatorArm64Test

      - name: Save Test Results
        uses: actions/upload-artifact@v6
        if: ${{ always() }}
        with:
          name: test-results-ios
          path: |
            **/build/reports/tests/
          retention-days: 7

  desktop-test:
    name: "Desktop"
    runs-on: macos-latest
    timeout-minutes: 80

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Run tests
        run: ./gradlew desktopTest

      - name: Save Test Results
        uses: actions/upload-artifact@v6
        if: ${{ always() }}
        with:
          name: test-results-desktop
          path: |
            **/build/reports/tests/
          retention-days: 7
